# Generated by Django 5.2.3 on 2025-08-17 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='analisados/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('resume_analyze', models.TextField(blank=True, null=True)),
                ('area_atuacao', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_senioridade', models.CharField(blank=True, max_length=255, null=True)),
                ('palavras_chave', models.JSONField(blank=True, null=True)),
                ('nome_vaga', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
