# Generated by Django 5.2.3 on 2025-06-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='analisados/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('resume_analyze', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
