# Generated by Django 5.2.3 on 2025-08-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzer',
            name='area_atuacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyzer',
            name='nivel_senioridade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyzer',
            name='nome_vaga',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyzer',
            name='palavras_chave',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
