# Generated by Django 5.2.3 on 2025-09-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzer',
            name='status',
            field=models.CharField(choices=[('NA_FILA', 'Na Fila'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('FALHA', 'Falha')], default='NA_FILA', max_length=20),
        ),
    ]
