# Generated by Django 5.2.3 on 2025-07-31 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_costumeruser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumeruser',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='costumeruser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='costumeruser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
