# Generated by Django 5.2.3 on 2025-08-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_costumeruser_is_employee_costumeruser_is_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumeruser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
